### ISSUE TITLE
Unnecessary comma in .csv-files for classCDEdges and packageCDEdges

### ISSUE THREAD

**Issue by justPrljant** [PhilippGnoyke/AsTdEA#2]
**Description**
All .csv-files regarding `classCDEdges` and `packageCDEdges` contain an unnecessary trailing comma in their first content row after the header. See the following screenshots from analysis of hibernate v1.0.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/29733570/234256954-b6ca2a14-5ef2-45a3-a73c-2db8c27603b2.png)
![grafik](https://user-images.githubusercontent.com/29733570/234257109-1916a692-9ce1-4f84-8e00-cf3219c6bb8a.png)
![grafik](https://user-images.githubusercontent.com/29733570/234257313-4af06b5b-3bf2-4b1d-b735-5423bb511c69.png)

**Comment by PhilippGnoyke** [comment]
Thanks for pointing that out. Fixed now.
